name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0, v1.0.0, etc.
permissions:
  contents: write
jobs:
  build:
    name: Build for all platforms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Specify your Go version

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/smpp-cli-linux-amd64 main.go
          GOOS=linux GOARCH=arm64 go build -o build/smpp-cli-linux-arm64 main.go
          GOOS=windows GOARCH=amd64 go build -o build/smpp-cli-windows-amd64.exe main.go
          GOOS=darwin GOARCH=amd64 go build -o build/smpp-cli-darwin-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o build/smpp-cli-darwin-arm64 main.go

      - name: Archive binaries
        run: |
          mkdir artifacts
          tar -czf artifacts/smpp-cli-linux-amd64.tar.gz -C build smpp-cli-linux-amd64
          tar -czf artifacts/smpp-cli-linux-arm64.tar.gz -C build smpp-cli-linux-arm64
          zip artifacts/smpp-cli-windows-amd64.zip build/smpp-cli-windows-amd64.exe
          tar -czf artifacts/smpp-cli-darwin-amd64.tar.gz -C build smpp-cli-darwin-amd64
          tar -czf artifacts/smpp-cli-darwin-arm64.tar.gz -C build smpp-cli-darwin-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smpp-cli-linux-amd64.${{github.ref}}.tar.gz -C build smpp-cli-linux-amd64
          path: artifacts/smpp-cli-linux-amd64.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smpp-cli-linux-arm64.${{github.ref}}.tar.gz
          path: artifacts/smpp-cli-linux-arm64.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smpp-cli-windows-amd64.${{github.ref}}.zip
          path: artifacts/smpp-cli-windows-amd64.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smpp-cli-darwin-amd64.${{github.ref}}.tar.gz
          path: artifacts/smpp-cli-darwin-amd64.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smpp-cli-darwin-arm64.${{github.ref}}.tar.gz
          path: artifacts/smpp-cli-darwin-arm64.tar.gz
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: smpp-cli-linux-amd64.${{github.ref}}.tar.gz, smpp-cli-linux-arm64.${{github.ref}}.tar.gz, smpp-cli-windows-amd64.${{github.ref}}.zip, smpp-cli-darwin-amd64.${{github.ref}}.tar.gz, smpp-cli-darwin-arm64.${{github.ref}}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for tag ${{ github.ref_name }}"
          allowUpdates: true
